version: '2.1'
services:
 database:
   container_name: db-sierraleone
   image: itellez/dhis2-db-demo:2.31
   environment:
     POSTGRES_USER: dhis
     POSTGRES_DB: dhis
     POSTGRES_PASSWORD: dhis
     POSTGRES_DB_TARGET: dhis-target
     PG_DATA: /var/lib/postgresql/data/pgdata:z
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -h database -d dhis2"]
     interval: 30s
     timeout: 30s
     retries: 150
 web:
   container_name: dhsi2-app
   image: itellez/dhis2-app:2.31
   environment:
     JAVA_OPTS: "-Xmx7000m -Xms4000m"
     POSTGRES_DB: dhis
   ports:
     - "8085:8080"
   depends_on:
     database:
       condition: service_healthy
   healthcheck:
     test: "curl -f http://web:8080"
     interval: 30s
     retries: 150